const path = {
  home: "/",
  login: "/login",
  logout: "/logout",
  forgotPassword: "/forgotPassword",
  sendCode: "/sendCode",
  register: "/register",
  phone: "/smartphone",
  laptop: "/laptop",
  tablet: "/tablet",
  smartwatch: "/smartwatch",
  accessory: "",
  cart: "/cart",
  history: "/history",
  voucher: "/voucher",
  pc: "/pc",
  dienthoaiDetail: "smartphone/detail/:productSlug",
  laptopDetail: "laptop/detail/:productSlug",
  tabletDetail: "tablet/detail/:productSlug",
  watchDetail: "watch/detail/:productSlug",
  monitor: "man-hinh-may-tinh/detail/:productSlug",
  maytinhdeban: "may-tinh-de-ban/detail/:productSlug",
  phukienDetail: "phukien/detail/:productSlug",
  smartwatchDetail: "smartwatch/detail/:productSlug",
  historyDetail: "history/detail/:id",
  ////
  user: "/user",
  profile: "/user/profile",
  changePassword: "/user/password",
  historyPurchase: "/user/purchase",
  cartNew: "/user/cartNew",
  sendCodeActive: "/user/sendCodeActive",
  activeAccount: "/user/activeAccount",
  payment: "/payment",
  comment: "/user/comment",
  search: "/search",
} as const;

export default path;

